name: tube_vibe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  chip_list: ^3.0.0
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  firebase_storage: ^11.7.5
  flick_video_player: ^0.7.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  provider: ^6.1.2
  responsive_grid_list: ^1.4.0
  textfield_tags: ^3.0.1
  timeago: ^3.6.1
  video_compress: ^3.0.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
